---

google:
  spreadsheet_id: '19fDDq9QyoN9aM-LnyCN7dbMynuD7yjMrvTSoizU_VZE'
  sheets:
    row_date_start: 5
    row_names_start: 4
logger:
  file:
    name: 'logs/app-{log_date}.log'
    date_format: '%m%d%-y-%H:%M:%S'
  content:
    text_format: '%(levelname)s:%(asctime)s:%(message)s'
    level: DEBUG
